-- DropIndex
DROP INDEX `users_role_idx` ON `users`;

-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('TASK_ASSIGNED', 'DEADLINE_APPROACHING', 'REVIEW_SCHEDULED', 'FEEDBACK_GIVEN', 'PROJECT_UPDATED', 'MILESTONE_DUE', 'PROJECT_SUBMITTED', 'FEEDBACK_ADDED', 'CHANGES_REQUESTED', 'PROJECT_APPROVED', 'PROJECT_PUBLISHED', 'TICKET_CREATED', 'TICKET_REPLIED') NOT NULL;
